name: naifarm
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  cupertino_icons: ^1.0.3
  shared_preferences: ^2.0.6
  basic_utils: ^3.3.3
  lottie: ^1.1.0
  flutter_svg: ^0.22.0
  google_fonts: ^2.1.0
  page_transition: ^2.0.2
  flutter_icons: ^1.1.0
  sqflite: ^2.0.0+3
  path_provider: ^2.0.2
  equatable: ^2.0.3
  dio: ^4.0.0
  logging: ^1.0.1
  rxdart: ^0.27.1
  cached_network_image: ^3.0.0
  smooth_star_rating: 1.1.1
  carousel_slider: ^4.0.0
  form_validator: ^0.1.7
  clipboard: ^0.1.3
  regexed_validator: ^1.0.4
  progress_dialog: ^1.2.4
  retrofit: ^2.0.0
  logger: ^1.0.0
  easy_localization: ^3.0.0
  sticky_headers: ^0.2.0
  custom_refresh_indicator: ^1.0.0
  flutter_spinkit: ^5.0.0
  timeline_tile: ^2.0.0
  dotted_border: ^2.0.0
  flutter_switch: ^0.3.2
  custom_dropdown: ^0.0.2
  modal_bottom_sheet: ^2.0.0
  keyboard_visibility: ^0.5.6
  flutter_screenutil: ^5.0.0+2
  nuts_activity_indicator: ^0.1.1
  flutter_countdown_timer: ^4.1.0
  image_picker: ^0.8.1+3
  permission_handler: ^8.1.2
  #google_maps_flutter: ^1.0.6
  #  location: ^3.2.4
  #  geolocator: ^6.2.0
  #  geocoder: ^0.2.1
  fdottedline: ^1.0.1
  vibration: ^1.7.3
  flutter_datetime_picker: ^1.5.1
  sizer: ^2.0.13
  skeleton_loader: ^2.0.0+4
  localstorage: ^4.0.0+1
  flutter_bloc: ^7.0.1
  multi_image_picker: ^4.8.1
  #audioplayers: ^0.17.2
  flutter_slidable: ^0.6.0
  full_screen_image: ^1.0.2
  badges: ^2.0.1
  #flutter_widget_from_html: ^0.3.3
  timeago: ^3.1.0
  share: ^2.0.4
  like_button: ^2.0.2
  onesignal_flutter: ^3.1.0
  flutter_html: ^2.1.0
  flutter_local_notifications: ^6.0.0
  #flutter_automation: ^1.4.0
  swipeable_page_route: ^0.2.2
  uni_links: ^0.5.1
  sign_in_with_apple: ^3.0.0
  package_info: ^2.0.2
  translator: ^0.1.7
  sms_autofill: ^2.0.1
  focused_menu: ^1.0.5
  rive: ^0.7.23
  flutter_login_facebook: ^1.0.1
  http: ^0.13.3
  url_launcher: ^6.0.9
  flutter_app_badger: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/json/
    - assets/images/svg/
    - assets/images/png/
    - resources/langs/
    - assets/sound/
    - assets/rive animation/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:fcf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
