# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
 
  desc "Distribute app via Firebase"
  lane :distribute_staging do
      firebase_app_distribution(
	app: "1:536378613546:ios:24fdb3fee18b35f44b0853",
	ipa_path:"./artifact/Naifarm-stag.ipa",
	testers: "ApisitKaewsasan@gmail.com",
	release_notes_file:"../release_notes.md",
	#groups:"tester"
     )
  end

  desc "Distribute app via Firebase"
  lane :distribute_prod do
      firebase_app_distribution(
	app: "1:891950861123:ios:7f56699585848cf23f3df6",
	ipa_path:"./artifact/Naifarm.ipa",
	testers: "ApisitKaewsasan@gmail.com",
	release_notes_file:"../release_notes.md",
	#groups:"tester"
     )
  end

  desc "Build Application and Export spa"
  lane :build_prod do
    gym(scheme: "",
	export_options: {
	  method: "ad-hoc",
	  provisioningProfiles: {
   	    "com.dotsocket.naifarm" => "Ad Hoc Distribution Naifarm"
           }
	},
	output_directory: "./artifact",
	output_name: "Naifarm.ipa")
  end

  desc "Build Application and Export spa"
  lane :build do
    gym(scheme: "",
	export_options: {
	  method: "ad-hoc",
	  provisioningProfiles: {
   	    "com.dotsocket.naifarm.staging" => "Ad Hoc Distribution"
           }
	},
	output_directory: "./artifact",
	output_name: "Naifarm-stag.ipa")
  end
end
